#coding: utf-8
import glob, os, subprocess, sys

src = glob.glob('src/*.c') + glob.glob('common/*.c') + glob.glob('lib/*.c')

CPPPATH = ['usr/local/include']

CCFLAGS='-Wall -g ' 
LINKFLAGS='-g '

if os.sys.platform in ["darwin", "linux2"]:
    CCFLAGS += " -D_GNU_SOURCE -DMONGO_HAVE_STDINT -DDEBUG" 

#Program( 'bin/', src, LIBS = LIBS, LIBPATH = LIBPATH, CPPPATH = CPPPATH, CCFLAGS = CCFLAGS)
SharedLibrary('prun', src, CPPPATH = CPPPATH, CCFLAGS = CCFLAGS)

